<a href="https://colab.research.google.com/github/vatsal30/Tensorflow_Deep_Learning/blob/main/notebooks/00_tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting started with TensorFlow

## What is Tensorflow?

[TensorFlow](https://www.tensorflow.org/) is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML powered applications.

## Why TensorFlow?


# Tensorflow Basics

### Tensor Basic and tf.constant()

In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
#create tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check dimension of tensor
scalar.ndim

0

In [4]:
#Create a vector
vector = tf.constant([10,20,30])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10,20],
                     [20,30]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 30]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
matrix_2 = tf.constant([[1.0,2.4],
                        [3.2,3.4],
                        [4.5,6.7]], dtype=tf.float16)
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1. , 2.4],
       [3.2, 3.4],
       [4.5, 6.7]], dtype=float16)>

In [9]:
matrix_2.ndim

2

In [10]:
tensor = tf.constant([[[1,2,3],
                       [3,4,5]],
                      [[6,7,8],
                       [7,8,9]],
                      [[1,2,3],
                       [3,4,5]],
                      [[6,7,8],
                       [7,8,9]]])
tensor

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[6, 7, 8],
        [7, 8, 9]],

       [[1, 2, 3],
        [3, 4, 5]],

       [[6, 7, 8],
        [7, 8, 9]]], dtype=int32)>

In [11]:
tensor.ndim

3

* Scalar: a single number
* Vector: a number with direction (eg. wind speed and direction)
* Matrix: a 2D array of numbers
* Tensor: a n-dimensional array of numbers

In [12]:
#Basic Math with tensors

a = tf.constant([[1,2],
                 [3,4]])
b = tf.ones([2,2], dtype=tf.int32)
print(a)
print(b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [13]:
# Addition
print((a + b))
print(tf.add(a,b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [14]:
#Element wise multiplication
print(a*b)
print(tf.multiply(a,b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [15]:
#Matrix Multiplication
print(a@b)
print(tf.matmul(a,b))

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [16]:
#Find max Value
c = tf.constant([[10 ,20 , 30], [78,32, 42]])

print("Max value: ", tf.reduce_max(c))

Max value:  tf.Tensor(78, shape=(), dtype=int32)


In [17]:
#Find max value location
tf.argmax(c)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 1])>

In [18]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

In [19]:
# Finding Shape
rank_4_tensor.shape

TensorShape([3, 2, 4, 5])

In [20]:
# Finding Size
tf.size(rank_4_tensor).numpy()

120

In [21]:
# Number of axes
rank_4_tensor.ndim

4

In [22]:
# Finding Datatype of Every Element
rank_4_tensor.dtype

tf.float32

In [23]:
#Indexing Single Index
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])

print("First Eleemnt: ", rank_1_tensor[0].numpy())
print("Last Element: ", rank_1_tensor[-1].numpy())

First Eleemnt:  0
Last Element:  34


In [24]:
print("Everything: ", rank_1_tensor[:].numpy())
print("Reverse: ", rank_1_tensor[::-1].numpy())
print("Element 2 to 6: ",rank_1_tensor[1:6].numpy())
print("Upto 5 Element:", rank_1_tensor[:5].numpy())

Everything:  [ 0  1  1  2  3  5  8 13 21 34]
Reverse:  [34 21 13  8  5  3  2  1  1  0]
Element 2 to 6:  [1 1 2 3 5]
Upto 5 Element: [0 1 1 2 3]


In [25]:
# Multi Index
matrix = tf.constant([[1.,2.],
 [3., 4.],
 [5., 6.]])
matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [26]:
# access any single element
print(matrix[2,1].numpy())

6.0


In [27]:
#Access Second Row
print(matrix[1].numpy())

[3. 4.]


In [28]:
#Access Second Column
print(matrix[:,1].numpy())

[2. 4. 6.]


In [29]:
# Access Last Row
print(matrix[-1].numpy())

[5. 6.]


In [30]:
# Type Conversion
x = tf.constant([2.4,3.6,4.2])
print(x)
x = tf.cast(x, dtype = tf.int32)
print(x)

tf.Tensor([2.4 3.6 4.2], shape=(3,), dtype=float32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [31]:
# BroadCasting: This is same as broadcasting in numpy
# under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.

y = tf.constant(2)
z= tf.constant([2,2,2])

print(tf.multiply(x,2))
print(tf.multiply(x,y))
print(tf.multiply(x,z))

tf.Tensor([4 6 8], shape=(3,), dtype=int32)
tf.Tensor([4 6 8], shape=(3,), dtype=int32)
tf.Tensor([4 6 8], shape=(3,), dtype=int32)


### tf.Variable()

In [32]:
# Cerate Tensors with tf.variable()
# A variable here is look like tensor and it is backed by tensor and have same methods as tensors
my_tensor = tf.constant([[1,2,3],[3,4,5]])
my_variable = tf.Variable([[1,2,3],[3,4,5]])

print(my_tensor)
print(my_variable)

tf.Tensor(
[[1 2 3]
 [3 4 5]], shape=(2, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>


In [33]:
# you cannot change tensor created by tf.constant
# This line will generate an error
my_tensor[1,0] = 6 

TypeError: ignored

In [ ]:
#If you try to assign Variable
my_variable[1,0] = 6

In [ ]:
# For assign any value in variable you need to use assign function
my_variable[1,0].assign(6)
my_variable

In [ ]:
# A variable looks and acts like a tensor, and, in fact, is a data structure backed by a tf.Tensor. 
# Like tensors, they have a dtype and a shape, and can be exported to NumPy.
print("Data Type: ", my_variable.dtype)
print("Shape: ", my_variable.shape)
print("Numpy Array: ", my_variable.numpy())


In [ ]:
# Change Variable to tensor
tf.convert_to_tensor(my_variable)

In [ ]:
# We cannot change shpare of variable same as tensor
# It will create new tensor not reshape existing variable
tf.reshape(my_variable,[3,2])

In [ ]:
# Find index of max value
tf.argmax(my_variable)

In [ ]:
# Find max value
tf.reduce_max(my_variable).numpy()

In [ ]:
# If we copy variable into another using tf.Variable it will create new variable
a = tf.Variable([1,2,3])
b = tf.Variable(a)

#adding into a
print(a.assign_add([3,4,5]).numpy())
print(b.numpy())

#subtrac from a
print(a.assign_sub([1,2,3]).numpy())
print(b.numpy())

In [ ]:
# Create a and b; they will have the same name but will be backed by
# different tensors.
a = tf.Variable(my_tensor, name="Mark")
# A new variable with the same name, but different value
# Note that the scalar add is broadcast
b = tf.Variable(my_tensor + 1, name="Mark")

print(a)
print(b)
# These are elementwise-unequal, despite having the same name
print(a == b)


### Creating Random Tensors
  Random Tensors are tenosrs of  some arbitrary size  which contain some random numbers.

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
print(random_1)
random_2 = tf.random.normal(shape=(3,2))
print(random_2)

### Shuffle tenosr Elements

In [ ]:
not_shuffled = tf.constant([[10, 7],
                            [20, 4],
                            [30, 5]])
not_shuffled.ndim 

In [ ]:
tf.random.shuffle(not_shuffled)

### tf.random.seed
Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

1. If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
2. If the graph-level seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the graph-level seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both graph-level and operation-level seeds explicitly.
3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.




In [ ]:
# If neither the global seed nor the operation seed is set, 
# we get different results for every call to the random op and every re-run of the program:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

In [ ]:
# If the global seed is set but the operation seed is not set, 
# we get different results for every call to the random op, but the same sequence for every re-run of the program:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

In [ ]:
# Rerun the program and run below lines it shows same results as above
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

> Note : `tf.function` acts like a re-run of a program in this case. When the global seed is set but operation seeds are not set, the sequence of random numbers are the same for each tf.function

In [ ]:
# If the operation seed is set,
# we get different results for every call to the random op, but the same sequence for every re-run of the program:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

In [ ]:
# Rerun the program and run below lines it shows same results as above
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

In [ ]:
# If both global and operation level seed are set we get same results for every run
tf.random.set_seed(1234)
print(tf.random.normal((3,2), seed=1234))

In [ ]:
# If You restart and run below cell than also it will return same result
tf.random.set_seed(1234)
print(tf.random.normal((3,2), seed=1234))

### Different ways of creating Tensors

In [ ]:
# creating tensors of all ones
tf.ones((10,7))

In [ ]:
# creating tensors of all zeros
tf.zeros((10, 7))

### creating tensors from NumPy array
The main difference between NumPy arrays and Tensorflow tensors is that tensors can run on GPUs (Faster Computing).

( You can use Jax to use NumPy array direcly to run on GPUs.) 

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) 
numpy_A

In [ ]:
A = tf.constant(numpy_A, shape = (2,3,4)) # 2 * 3 * 4 = 24
B = tf.constant (numpy_A, shape = (3,8)) # 8 * 3 = 24
A, B

### Getting information from Tensors
| Attribute | Code |
| :----------: | ---------------- |
| Shape | tensor.shape |
| Rank | tensor.ndim |
| Axis or dimension | tensor[0], tensor[:,-1]... |
| Size | tf.size(tensor) |




In [ ]:
# Creating Rank 4 Tensor 
rank_4_tensor = tf.zeros(shape = (2,3,4,5))
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
print("Shape : ", rank_4_tensor.shape)
print("Rank : ", rank_4_tensor.ndim)
print("Size : ", tf.size(rank_4_tensor).numpy())

In [ ]:
print("Data type of Every Eleemnt: ", rank_4_tensor.dtype)
print("Element along 0th axis: ", rank_4_tensor[0])
print("Element along with last axis: ", rank_4_tensor[-1])

### Indexing Tensors
Tensor can be index like Python List

In [ ]:
rank_4_tensor = tf.random.uniform(shape=(2,3,4,5), minval=0, maxval=120)
rank_4_tensor

In [ ]:
# Get First 2 Elemetns of Each Dimension
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Get First Element from Each dimension from each index except the final one
rank_4_tensor[ :1, :1, :1, :]

In [ ]:
# create rank 2 tensor
rank_2_tensor = tf.constant([[10, 20],
                             [20, 30]])
rank_2_tensor

In [ ]:
# Get Last Item of Each Row
rank_2_tensor[:, -1]

In [ ]:
# Adding Extra Diemention to rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1)

### Manipulating Tensors

Finding patterns in tensors (numberical representation of data) requires manipulating them

**Basic Operation**

We can perform most of the basic mathematical tensor operations directly on tensors using Python operators.
 `+`, `-`, `*`, `/`.

In [ ]:
a = tf.constant([[10, 20],
                 [30, 40]])
a, a+10

Here original tensor is not going to update it will create new copy for resulting tensor.

In [ ]:
a * 10

In [ ]:
a - 10

In [ ]:
a / 10

In [ ]:
tf.multiply(a, 10)

In [ ]:
tf.add(a, 10)

In [ ]:
tf.subtract(a, 10)

**Matrix Multiplication**


In [ ]:
tf.matmul(a, a)

In [ ]:
# In Python
a @ a

In [ ]:
x = tf.constant([[1, 2],
                 [3, 5],
                 [7, 2]])
y = tf.constant([[5, 2],
                 [5, 7],
                 [8, 9]])

In [ ]:
tf.matmul(x, y)

In [ ]:
x.shape, tf.reshape(y, shape=(2,3)).shape

In [ ]:
tf.matmul(x, tf.reshape(y, shape=(2,3)))

In [ ]:
tf.matmul(tf.reshape(x, shape=(2,3)), y)

In [ ]:
# Transpose OF martix
y, tf.transpose(y)