<a href="https://colab.research.google.com/github/vatsal30/Tensorflow_Deep_Learning/blob/main/notebooks/00_TensorFlow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting started with TensorFlow

## What is TensorFlow?

[TensorFlow](https://www.tensorflow.org/) is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML powered applications.





## Why TensorFlow?
![Tensorflow_Advantages](https://raw.githubusercontent.com/vatsal30/Tensorflow_Deep_Learning/main/notebooks/images/why_tensorflow.PNG)
Source: [TensorFlow](https://www.tensorflow.org/)

## Topics In this notebook

* Intro to Tensor
* Basic Tensor Operations
* Creating Variable ( tf.Variable())
* Basic Tensor Opearaions
* Getting Information From Tensor
* Tensor Manipulation
* Tensor and NumPy Array 
* Using @tf.function
* Using GPU



## Note
 I am learning from the Daniel Bourke's Github [Repo](https://github.com/mrdbourke/tensorflow-deep-learning) and all things are covered in this notebooks are from his notebooks. Please Checkout his course on tensorflow on [Udemy](https://www.udemy.com/course/tensorflow-developer-certificate-machine-learning-zero-to-mastery/)

  Also Many things are from official [Tensorflow Documentation](https://www.tensorflow.org/guide).

## Introduction to Tensors
 [Tensors](https://www.tensorflow.org/guide/tensor) are multi-dimensional arrays with a uniform type. It's Like Numpy [arrays](https://numpy.org/doc/stable/reference/generated/numpy.array.html)

 All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.

 Main difference between tensors and NumPy arrays is that a tensor can be run of GPUs and TPUs.


In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


### Creating Tensor With [`tf.constant()`](https://www.tensorflow.org/guide/tensor)

In [2]:
#create tensor with tf.constant()
rank_0_tensor = tf.constant(30)
rank_0_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=30>

This rank_0_tensor also known as scalar. A scalar tensor has no axis.

In [3]:
#check dimension of tensor
rank_0_tensor.ndim

0

In [4]:
#Create a rank_1_tensor
rank_1_tensor = tf.constant([10,20,30])
rank_1_tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

This rank_1_tensor is known as vector. A vector as one axis.

In [5]:
rank_1_tensor.ndim

1

In [6]:
rank_2_tensor  = tf.constant([[10,20],
                     [20,30]])
rank_2_tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 30]], dtype=int32)>

This rank_2_tensor is known as matrix and it has 2 axis.

In [7]:
rank_2_tensor.ndim

2

In [8]:
matrix_2 = tf.constant([[1.0,2.4],
                        [3.2,3.4],
                        [4.5,6.7]], dtype=tf.float16)
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1. , 2.4],
       [3.2, 3.4],
       [4.5, 6.7]], dtype=float16)>

In [9]:
matrix_2.ndim

2

In [10]:
rank_3_tensor = tf.constant([[[1,2,3],
                       [3,4,5]],
                      [[6,7,8],
                       [7,8,9]],
                      [[1,2,3],
                       [3,4,5]],
                      [[6,7,8],
                       [7,8,9]]])
rank_3_tensor

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[6, 7, 8],
        [7, 8, 9]],

       [[1, 2, 3],
        [3, 4, 5]],

       [[6, 7, 8],
        [7, 8, 9]]], dtype=int32)>

The tensor can also have more than 2 dimensions. All above scalar, vector, matrix are all tensors.

In [11]:
rank_3_tensor.ndim

3

* **Scalar**: a single number
* **Vector**: a 1D array of numbers 
* **Matrix**: a 2D array of numbers
* **Tensor**: a n-dimensional array of numbers.(n can be 0, 1, 2 or more than 2)

### Creating Tensors with [`tf.Varaible()`](https://www.tensorflow.org/guide/variable)
  We can create tensor with `tf.Varaible()`. This tensor can changes and we can assign values to this tensors.

  The main differnce between `tf.constant()` and `tf.Variable()` is tensor created by `tf.constant()` are immutable(can't be change) and tensor created by `tf.Variable()` are mutable (can be changed). 

In [12]:
# Cerate Tensors with tf.variable()
# A variable here is look like tensor and it is backed by tensor and have same methods as tensors
my_tensor = tf.constant([[1,2,3],[3,4,5]])
my_variable = tf.Variable([[1,2,3],[3,4,5]])

print(my_tensor)
print(my_variable)

tf.Tensor(
[[1 2 3]
 [3 4 5]], shape=(2, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>


Changing Constant Tensor

In [13]:
# you cannot change tensor created by tf.constant
# This line will generate an error
my_tensor[1,0] = 6 

TypeError: ignored

Changing elements of Variable

In [ ]:
#If you try to assign Variable
# It will generate an error we need .assign() function
my_variable[1,0] = 6

To change tensors created by `tf.Variable()` we need to use `tf.assign()` method.

In [ ]:
# For assign any value in variable you need to use assign function
my_variable[1,0].assign(6)
my_variable

### Creating Random Tensors

Random Tensors are tenosrs of  some arbitrary size  which contain some random numbers.

We can create random tensors by using the [`tf.random.Generator`](https://www.tensorflow.org/api_docs/python/tf/random/Generator) class.

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
print(random_1)
random_2 = tf.random.normal(shape=(3,2))
print(random_2)

Here [`tf.random.normal`](https://www.tensorflow.org/api_docs/python/tf/random/normal) gives return random values from a normal distribution.

To know more about normal distribution check this [video](https://www.youtube.com/watch?v=iYiOVISWXS4)

In [ ]:
random_uniform = tf.random.Generator.from_seed(42)
random_uniform = random_uniform.uniform(shape=(3,2), minval = 0, maxval= 16, dtype=tf.int32)
random_uniform

Here [`tf.random.uniform`](https://www.tensorflow.org/api_docs/python/tf/random/uniform) return random values from a uniform distribution.

To know more about uniform distribution check this videos.

Discrete: https://www.youtube.com/watch?v=cyIEhL92wiw

Continuous: https://www.youtube.com/watch?v=-qt8CPIadWQ

The random tensors we've made are actually [pseudorandom numbers](https://www.computerhope.com/jargon/p/pseudo-random.htm) (they appear as random, but really aren't).

If we set a seed we'll get the same random numbers (it  similar to `np.random.seed(42)`). 


If we change the seed than we get different numbers.

### Shuffle Tensor

Why we need to shuffle?

If we are training any classififcation modal and we have data by category than we need to shuffle that data before giving it to the modal to train.

In [ ]:
not_shuffled = tf.constant([[10, 7],
                            [20, 4],
                            [30, 5]])
not_shuffled.ndim 

In [ ]:
# we get different result every time we run this cell.
tf.random.shuffle(not_shuffled)

In [ ]:
# Now setting seed paramer to get same result every time
# But this not work in practical
tf.random.shuffle(not_shuffled, seed=42)

Why this not working? 

For Understandin this we need to under stand how seed works in tensorflow.

`tf.random.set_seed()` is explained below with its rules and example but we can find solution of our problem from the rule 4 of [1tf.random.set_seed()`](https://www.tensorflow.org/api_docs/python/tf/random/set_seed) the documentation.

In [ ]:
# Shuffle in the same order every time

# Set the global seed
tf.random.set_seed(42)

# set the operation level seed
tf.random.shuffle(not_shuffled, seed=7)

`tf.random.set_seed(42)` sets the global seed, and the `seed` parameter in `tf.random.shuffle(seed=7)` sets the operation seed.

Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds"

#### [`tf.random.set_seed()`](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)
Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

> 1. If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
2. If the graph-level seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the graph-level seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both graph-level and operation-level seeds explicitly.
3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.




In [14]:
# If neither the global seed nor the operation seed is set, 
# we get different results for every call to the random op and every re-run of the program:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.593308], shape=(1,), dtype=float32)
tf.Tensor([0.59961057], shape=(1,), dtype=float32)


In [15]:
# If the global seed is set but the operation seed is not set, 
# we get different results for every call to the random op, but the same sequence for every re-run of the program:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [16]:
# Rerun the program and run below lines it shows same results as above
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [17]:
# If the operation seed is set,
# we get different results for every call to the random op, but the same sequence for every re-run of the program:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [18]:
# Rerun the program and run below lines it shows same results as above
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.4243431], shape=(1,), dtype=float32)
tf.Tensor([0.92531705], shape=(1,), dtype=float32)


In [19]:
# If both global and operation level seed are set we get same results for every run
tf.random.set_seed(1234)
print(tf.random.normal((3,2), seed=1234))

tf.Tensor(
[[-0.12297685 -0.76935077]
 [-0.13165176  0.08304894]
 [-3.0015008   0.7919886 ]], shape=(3, 2), dtype=float32)


In [20]:
# If You restart and run below cell than also it will return same result
tf.random.set_seed(1234)
print(tf.random.normal((3,2), seed=1234))

tf.Tensor(
[[-0.12297685 -0.76935077]
 [-0.13165176  0.08304894]
 [-3.0015008   0.7919886 ]], shape=(3, 2), dtype=float32)


### Create Tensors of All ones and All zeros

We can use [`tf.ones()`](https://www.tensorflow.org/api_docs/python/tf/ones) to create tensor of all ones and [`tf.zeros()`](https://www.tensorflow.org/api_docs/python/tf/zeros) to create tensor of all zeros.

In [21]:
# creating tensors of all ones
tf.ones((10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
# creating tensors of all zeros
tf.zeros((10, 7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Create Tensors from Numpy Arrays
The main difference between NumPy arrays and Tensorflow tensors is that tensors can run on GPUs or TPUs (Faster Computing).

( You can use Jax to use NumPy array direcly to run on GPUs)

In [23]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) 
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

To convert Numpy array we have two ways we can use `tf.constant()` and pass Numpy Array as arguemnt.

Also we can directly convert Numoy arrays using `tf.conver_to_tensor()` 

In [24]:
A = tf.constant(numpy_A, shape = (2,3,4)) # 2 * 3 * 4 = 24
B = tf.constant (numpy_A, shape = (3,8)) # 8 * 3 = 24
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

### Create Tensor Using [`tf.convert_to_tensor()`](https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor)

We can  Python objects of various types to Tensor objects. It accepts Tensor objects, numpy arrays, Python lists, and Python scalars. Also we can `tf.Variable` to tf.Tensor using this function.

In [25]:
numpy_arr = np.array([[1,2],[3,4]])
print(numpy_arr)
python_list = [1,2,3,4,5]
print(python_list)
scalar = 7
print(scalar)
tensor_variable = tf.Variable(numpy_arr,shape=(2,2))
print(tensor_variable)

[[1 2]
 [3 4]]
[1, 2, 3, 4, 5]
7
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>


In [26]:
tensor_1 = tf.convert_to_tensor(numpy_arr)
print(tensor_1)
tensor_2 = tf.convert_to_tensor(python_list)
print(tensor_2)
tensor_3 = tf.convert_to_tensor(scalar)
print(tensor_3)
tensor_4 = tf.convert_to_tensor(tensor_variable)
print(tensor_4)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


### Ragged Tensor
A tensor with variable numbers of elements along some axis is called "ragged".
Use `tf.ragged.RaggedTensor` for ragged data.

If we have variable data for different rows we cannot create tensors.

In [27]:
# For variable column data tf.constant returns error
tf.constant([[1,2,3,4],
             [5,6],
             [7,8,9],
             [10]])

ValueError: ignored

In [ ]:
ragged_tensor = tf.ragged.constant([[1,2,3,4],
             [5,6],
             [7,8,9],
             [10]])
ragged_tensor

In [28]:
# ragged tensor has some exis with unknown lenght
ragged_tensor.shape

NameError: ignored

### Creating String Tensors

We can Create string tensors by providing dtype as `tf.string`

The strings are atomic and cannot be indexed the way Python strings are. The length of the string is not one of the axes of the tensor.

we can use [`tf.strings`](https://www.tensorflow.org/api_docs/python/tf/strings) functions to manipulate them.

In [ ]:
string_tensor = tf.constant([['a','brown', 'fox'],
                             ['a','red', 'tree']], dtype=tf.string)
string_tensor

In the above printout the `b` prefix indicates that `tf.string` dtype is not a unicode string, but a byte-string.

See the [Unicode Tutorial](https://www.tensorflow.org/tutorials/load_data/unicode) for more about working with unicode text in TensorFlow.

In [29]:
string_tensor = tf.constant(['one piece','naruto', 'Dragon ball super'], dtype=tf.string)
string_tensor

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'one piece', b'naruto', b'Dragon ball super'], dtype=object)>

In [30]:
# we can use functions of tf.strings on tf.string type tensors
print(tf.strings.split(string_tensor))
print(tf.strings.split(string_tensor).shape)

<tf.RaggedTensor [[b'one', b'piece'], [b'naruto'], [b'Dragon', b'ball', b'super']]>
(3, None)


Here if split string tensor it will create new ragged tensor.

In [31]:
# Also we can use tf.strings.to_number
number_tensor = tf.constant(["1, 2, 3, 4"])
print(number_tensor)

print(tf.strings.to_number(tf.strings.split(number_tensor, sep=", ")))

tf.Tensor([b'1, 2, 3, 4'], shape=(1,), dtype=string)
<tf.RaggedTensor [[1.0, 2.0, 3.0, 4.0]]>


### Creating Sparse Tensor

Sometimes, your data is sparse, like a very wide embedding space. TensorFlow supports [`tf.sparse.SparseTensor`](https://www.tensorflow.org/api_docs/python/tf/sparse/SparseTensor) and related operations to store sparse data efficiently.

In [32]:
#  Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0,2], [3,1]], values=[10,20], dense_shape=(5,3))

print(sparse_tensor)
print()
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 2]
 [3 1]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 3], shape=(2,), dtype=int64))

tf.Tensor(
[[ 0  0 10]
 [ 0  0  0]
 [ 0  0  0]
 [ 0 20  0]
 [ 0  0  0]], shape=(5, 3), dtype=int32)


Here `tf.sparse.SparseTensor` has 3 arguments.

* indices = need to specifie index of elements where we need to store values
* values = values to store to locations which we specifies in indices
* dense_shape = original shape of sparse tensor

## Getting information from Tensors

  Some times we need some information from the tensors. There is some tensor vocabulory we need to know :


* Shape: The length (number of elements) of each of the dimensions of a tensor.
* Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* Axis or Dimension: A particular dimension of a tensor.
* Size: The total number of items in the tensor.


| Attribute | Defination | Code |
| :----------: | ---- |---------------- |
| Shape | The length (number of elements) of each of the dimensions of a tensor.| tensor.shape |
| Rank | The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n. | tensor.ndim |
| Axis or dimension | A particular dimension of a tensor | tensor[0], tensor[:,-1]... |
| Size | he total number of items in the tensor. | tf.size(tensor) |




In [33]:
# Creating Rank 4 Tensor 
rank_4_tensor = tf.zeros(shape = (2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [34]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [35]:
print("Shape of Tensor : ", rank_4_tensor.shape)
print("Number or Dimension or Rank of Tensor : ", rank_4_tensor.ndim)
print("Total Number of Elements (Size) : ", tf.size(rank_4_tensor).numpy())
print("Data type of Every Eleemnt: ", rank_4_tensor.dtype)
print("Elements along 0th axis of Tensor: ", rank_4_tensor.shape[0])
print("Element along with last axis: ", rank_4_tensor.shape[-1])

Shape of Tensor :  (2, 3, 4, 5)
Number or Dimension or Rank of Tensor :  4
Total Number of Elements (Size) :  120
Data type of Every Eleemnt:  <dtype: 'float32'>
Elements along 0th axis of Tensor:  2
Element along with last axis:  5


## Acessing Tensor Elements (Indexing)
  We index tensor just like the Python List and access any elements from it.



> Note: We can use `.numpy()` method to convert tensor to numpy array

In [36]:
# Indexing Vector Tensor
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])

print("First Eleemnt: ", rank_1_tensor[0].numpy())
print("Last Element: ", rank_1_tensor[-1].numpy())
print("Everything: ", rank_1_tensor[:].numpy())
print("Reverse: ", rank_1_tensor[::-1].numpy())
print("Element 2 to 6: ",rank_1_tensor[1:6].numpy())
print("Upto 5 Element:", rank_1_tensor[:5].numpy())

First Eleemnt:  0
Last Element:  34
Everything:  [ 0  1  1  2  3  5  8 13 21 34]
Reverse:  [34 21 13  8  5  3  2  1  1  0]
Element 2 to 6:  [1 1 2 3 5]
Upto 5 Element: [0 1 1 2 3]


In [37]:
# Indexing Matrix Tensor
matrix = tf.constant([[1.,2.],
 [3., 4.],
 [5., 6.]])
print(matrix)
print("\nSecond Element of 3rd Row: ", matrix[2,1].numpy())
print("Second Row: ",matrix[1].numpy())
print("Second Column: ", matrix[:,1].numpy())
print("Last Row: ", matrix[-1,:].numpy())

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)

Second Element of 3rd Row:  6.0
Second Row:  [3. 4.]
Second Column:  [2. 4. 6.]
Last Row:  [5. 6.]


In [38]:
# Indexing tensor with n dimension
rank_4_tensor = tf.random.uniform(shape=(2,3,4,5), minval=0, maxval=120)

In [39]:
# Elements along 0th axis:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[ 64.56472  ,  43.75424  ,  69.795616 ,  29.25941  ,
          51.640278 ],
        [108.74295  ,  60.86649  ,  43.058136 ,  93.46192  ,
          70.23625  ],
        [ 92.25759  ,  57.990845 ,  70.48675  ,   2.7240229,
          52.27863  ],
        [117.38875  , 117.72845  ,  17.577724 , 119.34875  ,
          93.763504 ]],

       [[ 26.415638 ,  58.679153 ,  75.97488  ,  67.64846  ,
          48.439964 ],
        [ 47.843956 ,  81.92328  ,  92.8955   ,  53.462463 ,
           6.821966 ],
        [ 29.514284 ,  36.637802 ,  38.083233 ,  23.161911 ,
          99.018776 ],
        [ 71.07831  ,  44.927444 , 101.20032  ,  28.850985 ,
          98.65455  ]],

       [[ 19.498701 ,  32.06696  ,  49.544735 ,  70.94456  ,
          77.37473  ],
        [ 37.933517 , 119.11529  ,  91.08337  ,  49.296913 ,
          24.41557  ],
        [ 53.345474 ,   2.813673 , 117.628296 , 102.42418  ,
           5.801139 ],
        [116.722015 ,

In [40]:
# Element along with last axis:
rank_4_tensor[-2]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[ 64.56472  ,  43.75424  ,  69.795616 ,  29.25941  ,
          51.640278 ],
        [108.74295  ,  60.86649  ,  43.058136 ,  93.46192  ,
          70.23625  ],
        [ 92.25759  ,  57.990845 ,  70.48675  ,   2.7240229,
          52.27863  ],
        [117.38875  , 117.72845  ,  17.577724 , 119.34875  ,
          93.763504 ]],

       [[ 26.415638 ,  58.679153 ,  75.97488  ,  67.64846  ,
          48.439964 ],
        [ 47.843956 ,  81.92328  ,  92.8955   ,  53.462463 ,
           6.821966 ],
        [ 29.514284 ,  36.637802 ,  38.083233 ,  23.161911 ,
          99.018776 ],
        [ 71.07831  ,  44.927444 , 101.20032  ,  28.850985 ,
          98.65455  ]],

       [[ 19.498701 ,  32.06696  ,  49.544735 ,  70.94456  ,
          77.37473  ],
        [ 37.933517 , 119.11529  ,  91.08337  ,  49.296913 ,
          24.41557  ],
        [ 53.345474 ,   2.813673 , 117.628296 , 102.42418  ,
           5.801139 ],
        [116.722015 ,

In [41]:
# Get First 2 Elemetns of Each Dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[ 64.56472 ,  43.75424 ],
         [108.74295 ,  60.86649 ]],

        [[ 26.415638,  58.679153],
         [ 47.843956,  81.92328 ]]],


       [[[ 53.768265,  33.721703],
         [ 88.636665,  75.23728 ]],

        [[ 33.613785,  77.74585 ],
         [ 82.87511 ,  90.18487 ]]]], dtype=float32)>

In [42]:
# Get First Element from Each dimension from each index except the final one
rank_4_tensor[ :1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=
array([[[[64.56472 , 43.75424 , 69.795616, 29.25941 , 51.640278]]]],
      dtype=float32)>

In [43]:
# create rank 2 tensor
rank_2_tensor = tf.constant([[10, 20],
                             [20, 30]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 30]], dtype=int32)>

In [44]:
# Get Last Item of Each Row
rank_2_tensor[:, -1].numpy()

array([20, 30], dtype=int32)

## Manipulating Tensors

Finding patterns in tensors (numberical representation of data) requires manipulating them.

Again, when building models in TensorFlow, much of this pattern discovery is done for you.

### Basic Operation

We can perform most of the basic mathematical tensor operations directly on tensors using Python operators.
 `+`, `-`, `*`, `/`.

In [45]:
a = tf.constant([[10, 20],
                 [30, 40]])
a, a+10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 30],
        [40, 50]], dtype=int32)>)

Here original tensor is not going to update it will create new copy for resulting tensor.

In [46]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [47]:
a * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [300, 400]], dtype=int32)>

In [48]:
a - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, 10],
       [20, 30]], dtype=int32)>

In [49]:
a / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

You can also use the equivalent TensorFlow function. Using the TensorFlow function (where possible) has the advantage of being sped up later down the line when running as part of a [TensorFlow graph](https://www.tensorflow.org/tensorboard/graphs).

In [50]:
tf.multiply(a, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [300, 400]], dtype=int32)>

In [51]:
tf.add(a, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [40, 50]], dtype=int32)>

In [52]:
tf.subtract(a, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, 10],
       [20, 30]], dtype=int32)>

In [53]:
a = tf.constant([[1,2],
                 [3,4]])
b = tf.ones([2,2], dtype=tf.int32)
print(a)
print(b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [54]:
# Addition
print((a + b))
print(tf.add(a,b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [55]:
#Element wise multiplication
print(a*b)
print(tf.multiply(a,b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### Matrix mutliplication
One of the most common operations in machine learning algorithms is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

TensorFlow implements this matrix multiplication functionality in the [`tf.matmul()`](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul) method.

In Python we have `@` Operator for matrix multiplication.

The main two rules for matrix multiplication to remember are:
1. The inner dimensions must match:
  * `(3, 5) @ (3, 5)` won't work
  * `(5, 3) @ (3, 5)` will work
  * `(3, 5) @ (5, 3)` will work
2. The resulting matrix has the shape of the outer dimensions:
 * `(5, 3) @ (3, 5)` -> `(5, 5)`

In [56]:
#Matrix Multiplication
print(a@b)
print(tf.matmul(a,b))

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [57]:
tf.matmul(a, a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [58]:
# In Python
a @ a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

Above Example is worked because they have same shape (2,2).

But if shapes are mismatched than?

In [59]:
X = tf.constant([[1, 2],
                 [3, 5],
                 [7, 2]])
Y = tf.constant([[5, 2],
                 [5, 7],
                 [8, 9]])

In [60]:
# Matrix multiply will return error
tf.matmul(X, Y)

InvalidArgumentError: ignored

Here we are trying to multiply two tensors with shape `(3,2)` which returns error because inner dimension don't match.

We need to either:
* Reshape X to `(2, 3)`. This will gives  `(2,3) @ (3,2) => (2,2)`
* Reshape Y to `(2, 3)`. This will gives  `(3,2) @ (2,3) => (3,3)`

We can decide where we need to resize X or Y based on the what shape we want in resultant matrix.

We can do this with either:
* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape) - allows us to reshape a tensor into a defined shape.
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) - switches the dimensions of a given tensor.


**Try with `tf.reshape()`**

In [61]:
# Example of reshape (3, 2) -> (2, 3)
X.shape, tf.reshape(Y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [62]:
# Matrix Multiplication with reshaped Y and python operator
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 18, 23],
       [50, 46, 60],
       [49, 30, 53]], dtype=int32)>

In [63]:
# Matrix Multiplication with reshaped X and tf.matmul
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[39, 43],
       [76, 77]], dtype=int32)>

**Try with [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose)**

In [64]:
# Example of transpose (3,2) -> (2,3)
y, tf.transpose(y)

NameError: ignored

In [ ]:
# Try matrix multiplication 
tf.matmul(tf.transpose(X), Y)

In [65]:
# Also we can create same result using parameters of `tf.matmul()`
tf.matmul(X, Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[76, 86],
       [51, 57]], dtype=int32)>

Here we can see that while using `tf.reshape()` and `tf.transpose()` returns different results .

In [66]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 19, 26],
       [25, 50, 69],
       [39, 49, 74]], dtype=int32)>

In [67]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 18, 23],
       [50, 46, 60],
       [49, 30, 53]], dtype=int32)>

Here we are changing shape of Y to `(2,3)` by using both functions but resulting values of Y is different for both function.

In [68]:
print(f'Original Y : \n {Y} \n')
print(f'Reshaped Y Shape (2,3) : \n {tf.reshape(Y, shape=(2,3))} \n')
print(f'Transposed Y Shape (2,3) : \n {tf.transpose(Y)} \n')

Original Y : 
 [[5 2]
 [5 7]
 [8 9]] 

Reshaped Y Shape (2,3) : 
 [[5 2 5]
 [7 8 9]] 

Transposed Y Shape (2,3) : 
 [[5 5 8]
 [2 7 9]] 



As you can see, the outputs of `tf.reshape()` and `tf.transpose()` when called on `Y`, even though they have the same shape, are different.

This can be explained by the default behaviour of each method:
* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape) - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the [`perm` parameter](https://www.tensorflow.org/api_docs/python/tf/transpose).

### The dot product

Multiplying matrices by eachother is also referred to as the dot product.

You can perform the `tf.matmul()` operation using [`tf.tensordot()`](https://www.tensorflow.org/api_docs/python/tf/tensordot).

In [69]:
tf.tensordot(X, tf.reshape(X, shape=(2,3)), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 16,  7],
       [28, 41, 19],
       [17, 28, 25]], dtype=int32)>

### Changing the datatype of a tensor

Sometimes you'll want to alter the default datatype of your tensor. 

This is common when you want to compute using less precision (e.g. 16-bit floating point numbers vs. 32-bit floating point numbers). 

Computing with less precision is useful on devices with less computing capacity such as mobile devices (because the less bits, the less space the computations require).

You can change the datatype of a tensor using [`tf.cast()`](https://www.tensorflow.org/api_docs/python/tf/cast).

In [70]:
A =  tf.constant([2.4,3.6,4.2])
print("Datatype of A : ", A.dtype)
B = tf.constant([3, 4, 5])
print("Datatype of B : ", B.dtype)

Datatype of A :  <dtype: 'float32'>
Datatype of B :  <dtype: 'int32'>


In [71]:
# Type Conversion From float32 to float16 (Reduced Precision)
C = tf.cast(A, dtype=tf.float16)
print(C)

# Type Conversion From int32 to int16 (Reduced Precision)
D = tf.cast(B, dtype=tf.int16)
print(D)

# Type Conversion From int32 to float32
B = tf.cast(B, dtype=tf.float32)
print(B)

# Type Conversion from float32 to int32 
A = tf.cast(A, dtype=tf.int32)
print(A)

tf.Tensor([2.4 3.6 4.2], shape=(3,), dtype=float16)
tf.Tensor([3 4 5], shape=(3,), dtype=int16)
tf.Tensor([3. 4. 5.], shape=(3,), dtype=float32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)


### Getting the absolute value
we can use [`tf.abs()`](https://www.tensorflow.org/api_docs/python/tf/math/abs).

In [72]:
neg_tensor = tf.constant([-4, -5])
pos_tensor = tf.abs(neg_tensor)

print(neg_tensor)
print(pos_tensor)

tf.Tensor([-4 -5], shape=(2,), dtype=int32)
tf.Tensor([4 5], shape=(2,), dtype=int32)


### Finding the min, max, mean, sum (aggregation)
You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax `reduce()_[action]`, such as:
* [`tf.reduce_min()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min) - find the minimum value in a tensor.
* [`tf.reduce_max()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max) - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
* [`tf.reduce_mean()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean) - find the mean of all elements in a tensor.
* [`tf.reduce_sum()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum) - find the sum of all elements in a tensor.
*[`tf.reduce_std()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_std) - find the standard deviation of all elements in a tensor.
*[`tf.reduce_variance()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_variance) - find the variance of the all elements in a tensor.
* **Note:** typically, each of these is under the `math` module, e.g. `tf.math.reduce_min()` but you can use the alias `tf.reduce_min()`.

In [73]:
#Find max Value
tensor_30 = tf.constant(np.random.randint(low=0, high=100, size=[30]),shape=(30,1),dtype=tf.float32)

print("Min value: ", tf.reduce_min(tensor_30))
print("Max value: ", tf.reduce_max(tensor_30))
print("Sum: ", tf.reduce_sum(tensor_30))
print("Mean: ", tf.reduce_mean(tensor_30))
print("Variance: ", tf.math.reduce_variance(tensor_30))
print("Standard Deviation: ", tf.math.reduce_std(tensor_30))

Min value:  tf.Tensor(1.0, shape=(), dtype=float32)
Max value:  tf.Tensor(94.0, shape=(), dtype=float32)
Sum:  tf.Tensor(1388.0, shape=(), dtype=float32)
Mean:  tf.Tensor(46.266666, shape=(), dtype=float32)
Variance:  tf.Tensor(692.9289, shape=(), dtype=float32)
Standard Deviation:  tf.Tensor(26.323542, shape=(), dtype=float32)


### Finding the positional maximum and minimum
* [`tf.argmax()`](https://www.tensorflow.org/api_docs/python/tf/math/argmax) - find the position of the maximum element in a given tensor.
* [`tf.argmin()`](https://www.tensorflow.org/api_docs/python/tf/math/argmin) - find the position of the minimum element in a given tensor.

In [74]:
#Find max value location
max_idx = tf.argmax(tensor_30)
print(max_idx.numpy())
print(tensor_30[max_idx[0]].numpy())

[1]
[94.]


In [75]:
#Find min value location
min_idx = tf.argmin(tensor_30)
print(min_idx.numpy())
print(tensor_30[min_idx[0]].numpy())

[4]
[1.]


### Squeezing a tensor (removing all single dimensions)

If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use `tf.squeeze()`.

* [`tf.squeeze()`](https://www.tensorflow.org/api_docs/python/tf/squeeze) - remove all dimensions of 1 from a tensor.

In [76]:
V = tf.fill([1,1,1,1,10],7)
print(V)
print(V.shape)
print(V.ndim)

tf.Tensor([[[[[7 7 7 7 7 7 7 7 7 7]]]]], shape=(1, 1, 1, 1, 10), dtype=int32)
(1, 1, 1, 1, 10)
5


In [77]:
V_squeezed = tf.squeeze(V)
print(V_squeezed.shape)
print(V_squeezed.ndim)
print(V_squeezed)

(10,)
1
tf.Tensor([7 7 7 7 7 7 7 7 7 7], shape=(10,), dtype=int32)


### Adding New Axis

We can also add dimensions to our tensor while keeping the same information present using tf.newaxis. 

In [78]:
# Adding Extra Diemention to rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [20]],

       [[20],
        [30]]], dtype=int32)>

We can achieve the same using [`tf.expand_dims()`](https://www.tensorflow.org/api_docs/python/tf/expand_dims).

In [79]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [20]],

       [[20],
        [30]]], dtype=int32)>

In [80]:
tf.expand_dims(rank_2_tensor, axis=0) #Adding new outer axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10, 20],
        [20, 30]]], dtype=int32)>

### BroadCasting
This is same as broadcasting in numpy.

Under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.


In [81]:
x = tf.constant([[5,4,3],
                 [3,4,5],
                 [4,5,6]])
y = tf.constant([2])
z= tf.constant([[2,2,2]])

print(x.shape)
print(y.shape)
print(z.shape)
print(tf.multiply(x,2))
print(tf.multiply(x,y))
print(tf.multiply(x,z))

(3, 3)
(1,)
(1, 3)
tf.Tensor(
[[10  8  6]
 [ 6  8 10]
 [ 8 10 12]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[10  8  6]
 [ 6  8 10]
 [ 8 10 12]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[10  8  6]
 [ 6  8 10]
 [ 8 10 12]], shape=(3, 3), dtype=int32)


Here above all 3 results are same.

First scalar 2 is scaled to `(3, 3)` matrix. 

Second Vector is scaled to `(3,3)` matrix.

Third Matrix also scaled to `(3,3)` matrix. 

All Looked Like this:
`[[2, 2, 2],
 [2, 2, 2],
 [2, 2, 2]]`

### One-hot encoding

If you have a tensor of indicies and would like to one-hot encode it, you can use [`tf.one_hot()`](https://www.tensorflow.org/api_docs/python/tf/one_hot).

You should also specify the `depth` parameter (the level which you want to one-hot encode to).

In [82]:
list = [1,2,3,4]

one_hot = tf.one_hot(list, depth=4)
one_hot

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [83]:
# Specify on and off values for encoding
one_hot = tf.one_hot(list, depth=4, on_value="Win", off_value="Lose")
one_hot

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Lose', b'Win', b'Lose', b'Lose'],
       [b'Lose', b'Lose', b'Win', b'Lose'],
       [b'Lose', b'Lose', b'Lose', b'Win'],
       [b'Lose', b'Lose', b'Lose', b'Lose']], dtype=object)>

### Squaring, log, square root

Many other common mathematical operations you'd like to perform at some stage, probably exist.

Let's take a look at:
* [`tf.square()`](https://www.tensorflow.org/api_docs/python/tf/math/square) - get the square of every value in a tensor. 
* [`tf.sqrt()`](https://www.tensorflow.org/api_docs/python/tf/math/sqrt) - get the squareroot of every value in a tensor (**note:** the elements need to be floats or this will error).
* [`tf.math.log()`](https://www.tensorflow.org/api_docs/python/tf/math/log) - get the natural log of every value in a tensor (elements need to floats).

In [84]:
tensor = tf.constant([7,8,9])
squared_tensor = tf.square(tensor)


print(tensor)
print(squared_tensor)

tf.Tensor([7 8 9], shape=(3,), dtype=int32)
tf.Tensor([49 64 81], shape=(3,), dtype=int32)


In [85]:
# Find the squareroot (will error), needs to be non-integer
root_tensor = tf.sqrt(squared_tensor)

InvalidArgumentError: ignored

In [ ]:
squared_tensor = tf.cast(squared_tensor, dtype=tf.float32)
root_tensor = tf.sqrt(squared_tensor)
root_tensor

In [86]:
log_tensor = tf.math.log(root_tensor)
log_tensor

NameError: ignored

## More On Variables

In [ ]:
my_variable = tf.Variable([[1,2,3],[3,4,5]])
my_variable

In [87]:
# Change Variable to tensor
tf.convert_to_tensor(my_variable)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [88]:
# A variable looks and acts like a tensor, and, in fact, is a data structure backed by a tf.Tensor. 
# Like tensors, they have a dtype and a shape, and can be exported to NumPy.
print("Data Type: ", my_variable.dtype)
print("Shape: ", my_variable.shape)
print("Numpy Array: ", my_variable.numpy())

Data Type:  <dtype: 'int32'>
Shape:  (2, 3)
Numpy Array:  [[1 2 3]
 [3 4 5]]


Tensors created with `tf.Variable()` can be changed in place using methods such as:

* [`.assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign) - assign a different value to a particular index of a variable tensor.
* [`.assign_add()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign_add) - add to an existing value and reassign it at a particular index of a variable tensor.
* [`.assign_sub()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign_sub) - subtract to an existing value and reassign it at a particular index of a variable tensor.

In [89]:
my_variable[0,2].assign(11)
my_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 1,  2, 11],
       [ 3,  4,  5]], dtype=int32)>

In [90]:
my_variable.assign_add([[0,0,0],[0,5,0]])
my_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 1,  2, 11],
       [ 3,  9,  5]], dtype=int32)>

In [91]:
my_variable.assign_sub([[0,0,0],[0,0,5]])
my_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 1,  2, 11],
       [ 3,  9,  0]], dtype=int32)>

In [92]:
# If we copy variable into another using tf.Variable it will create new variable
a = tf.Variable([1,2,3])
b = tf.Variable(a)

#adding into a
print(a.assign_add([3,4,5]).numpy())
print(b.numpy())

#subtract from a
print(a.assign_sub([1,2,3]).numpy())
print(b.numpy())

[4 6 8]
[1 2 3]
[3 4 5]
[1 2 3]


In [93]:
# Create a and b; they will have the same name but will be backed by
# different tensors.
a = tf.Variable(my_tensor, name="Mark")
# A new variable with the same name, but different value
b = tf.Variable(my_tensor + 1, name="Mark")

print(a)
print(b)
# These are elementwise-unequal, despite having the same name
print(a == b)


<tf.Variable 'Mark:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>
<tf.Variable 'Mark:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 4],
       [4, 5, 6]], dtype=int32)>
tf.Tensor(
[[False False False]
 [False False False]], shape=(2, 3), dtype=bool)


In [94]:
# We cannot change shpare of variable same as tensor
# It will create new tensor not reshape existing variable
tf.reshape(my_variable,[3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [11,  3],
       [ 9,  0]], dtype=int32)>

In [95]:
# Find index of max value
tf.argmax(my_variable)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 0])>

In [96]:
# Find max value
tf.reduce_max(my_variable).numpy()

11

## Tensors and NumPy

We've seen some examples of tensors interact with NumPy arrays, such as, using NumPy arrays to create tensors. 

Tensors can also be converted to NumPy arrays using:

* `np.array()` - pass a tensor to convert to an ndarray (NumPy's main datatype).
* `tensor.numpy()` - call on a tensor to convert to an ndarray.

Doing this is helpful as it makes tensors iterable as well as allows us to use any of NumPy's methods on them.

In [97]:
tensor = tf.constant(np.array([3., 5., 9.]))
tensor

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 5., 9.])>

In [98]:
# Convert back to numpy array using np.array()
np.array(tensor), type(np.array(tensor))

(array([3., 5., 9.]), numpy.ndarray)

In [99]:
# Convert back to numpy array using tensor.numpy()
tensor.numpy(), type(tensor.numpy())

(array([3., 5., 9.]), numpy.ndarray)

By default tensors have dtype=float32, where as NumPy arrays have dtype=float64.

This is because neural networks (which are usually built with TensorFlow) can generally work very well with less precision (32-bit rather than 64-bit).

In [100]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Using `@tf.function`

In your TensorFlow adventures, you might come across Python functions which have the decorator [`@tf.function`](https://www.tensorflow.org/api_docs/python/tf/function).

If you aren't sure what Python decorators do, [read RealPython's guide on them](https://realpython.com/primer-on-python-decorators/).

But in short, decorators modify a function in one way or another.

In the `@tf.function` decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with `@tf.function`, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

For more on this, read the [Better performnace with tf.function](https://www.tensorflow.org/guide/function) guide.

In [101]:
# Simple Function
def func(x, y):
  return x ** 2 + y ** 2

x = tf.constant([5,6])
y = tf.constant([3,9])
func(x, y)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 34, 117], dtype=int32)>

In [102]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_func(x, y):
  return x ** 2 + y ** 2

tf_func(x, y)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 34, 117], dtype=int32)>

If you noticed no difference between the above two functions (the decorated one and the non-decorated one) you'd be right.

Much of the difference happens behind the scenes. One of the main ones being potential code speed-ups where possible.


## Finding access to GPUs
You can check if you've got access to a GPU using [`tf.config.list_physical_devices()`](https://www.tensorflow.org/guide/gpu).

In [103]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


If the above outputs an empty array (or nothing), it means you don't have access to a GPU (or at least TensorFlow can't find it).

If you're running in Google Colab, you can access a GPU by going to *Runtime -> Change Runtime Type -> Select GPU* (**note:** after doing this your notebook will restart and any variables you've saved will be lost).

Once you've changed your runtime type, run the cell below.

In [104]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


If you've got access to a GPU, the cell above should output something like:

`[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]`

You can also find information about your GPU using `!nvidia-smi`.

In [105]:
!nvidia-smi

Sat May  8 18:39:57 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P0    31W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

> Note : If GPU is avialable tensorflow automatically detect it and use it.

# Practice Exercises

In [106]:
import tensorflow as tf
import numpy as np

In [107]:
# Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
scalar = tf.constant(30)
vector = tf.constant([30,60])
matrix = tf.constant([[10,20],
                      [30,40]])
tensor = tf.constant(np.random.randint(0, high=100, size=60),shape=(2,3,5,2))

print(f"Scalar : \n {scalar} \n")
print(f"Vector : \n {vector} \n")
print(f"martix : \n {matrix} \n")
print(f"Tensor : \n {tensor} \n")

Scalar : 
 30 

Vector : 
 [30 60] 

martix : 
 [[10 20]
 [30 40]] 

Tensor : 
 [[[[49 55]
   [87  1]
   [41 90]
   [68 12]
   [55 82]]

  [[72  9]
   [34  9]
   [26 90]
   [93 54]
   [77  5]]

  [[97 36]
   [30  7]
   [72 94]
   [ 5 98]
   [48 22]]]


 [[[73 78]
   [67 45]
   [59 99]
   [63 13]
   [85 87]]

  [[87 37]
   [57 52]
   [10 81]
   [53 71]
   [47 30]]

  [[35 65]
   [14 92]
   [96 29]
   [52 88]
   [38 43]]]] 



In [108]:
# Find the shape, rank and size of the tensors you created in 1.

def tensor_detail(tensor):
  print(f"Shape: {tensor.shape}")
  print(f"Rank: {tensor.ndim}")
  print(f"Size: {tf.size(tensor)}")
  print()

tensor_detail(scalar)
tensor_detail(vector)
tensor_detail(matrix)
tensor_detail(tensor)

Shape: ()
Rank: 0
Size: 1

Shape: (2,)
Rank: 1
Size: 2

Shape: (2, 2)
Rank: 2
Size: 4

Shape: (2, 3, 5, 2)
Rank: 4
Size: 60



In [109]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300].

def create_tensor(shape):
  return tf.random.uniform(minval=0, maxval=1, shape=shape)

tensor_1 = create_tensor((5,300))
tensor_2 = create_tensor((5,300))
print(tensor_1)
print("\n", tensor_2)

tf.Tensor(
[[0.3253647  0.1387006  0.64804935 ... 0.8244524  0.4551177  0.6277561 ]
 [0.49481273 0.41021204 0.7925637  ... 0.140463   0.2930702  0.00153995]
 [0.2957046  0.2699318  0.9645442  ... 0.32897913 0.6769521  0.5482559 ]
 [0.62759995 0.14295197 0.55955315 ... 0.46164548 0.1602869  0.6124419 ]
 [0.3618859  0.34776545 0.9293705  ... 0.15654767 0.7420492  0.08763742]], shape=(5, 300), dtype=float32)

 tf.Tensor(
[[0.59750986 0.30313778 0.99768174 ... 0.658538   0.9211241  0.41844308]
 [0.34860277 0.9065554  0.9254097  ... 0.35388374 0.7969308  0.7259033 ]
 [0.5854676  0.64556706 0.18183362 ... 0.75273776 0.29313827 0.5827645 ]
 [0.5377177  0.5112804  0.6758125  ... 0.558059   0.60013425 0.66264784]
 [0.48551023 0.0624429  0.14665365 ... 0.97490335 0.18743122 0.68693733]], shape=(5, 300), dtype=float32)


In [110]:
# Multiply the two tensors you created in 3 using matrix multiplication.
tf.matmul(tensor_1, tf.transpose(tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.55534 , 79.76474 , 78.0599  , 78.66237 , 74.04376 ],
       [76.611885, 82.060524, 81.421844, 81.308685, 77.484276],
       [76.64205 , 83.911026, 80.73897 , 80.07566 , 76.44371 ],
       [72.72066 , 80.515526, 79.37304 , 76.53802 , 71.54925 ],
       [74.096436, 79.94893 , 77.14867 , 78.38736 , 74.74268 ]],
      dtype=float32)>

In [111]:
# Multiply the two tensors you created in 3 using dot product.
tf.tensordot(tensor_1, tf.transpose(tensor_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.55534 , 79.76474 , 78.0599  , 78.66237 , 74.04376 ],
       [76.611885, 82.060524, 81.421844, 81.308685, 77.484276],
       [76.64205 , 83.911026, 80.73897 , 80.07566 , 76.44371 ],
       [72.72066 , 80.515526, 79.37304 , 76.53802 , 71.54925 ],
       [74.096436, 79.94893 , 77.14867 , 78.38736 , 74.74268 ]],
      dtype=float32)>

In [112]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor_3 = create_tensor((224,224,3))
tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.9099175 , 0.6676756 , 0.19938636],
        [0.3284049 , 0.04517746, 0.5198144 ],
        [0.5085689 , 0.3789295 , 0.58378994],
        ...,
        [0.21674263, 0.5635047 , 0.47372687],
        [0.7644787 , 0.10901237, 0.17862225],
        [0.8508351 , 0.90439844, 0.73274577]],

       [[0.5905173 , 0.7619034 , 0.30757678],
        [0.12660551, 0.45299566, 0.26390076],
        [0.83228934, 0.6325017 , 0.86080575],
        ...,
        [0.83879304, 0.6170857 , 0.20510781],
        [0.90482044, 0.70842016, 0.2637738 ],
        [0.7711698 , 0.84586656, 0.98501253]],

       [[0.34203315, 0.9504638 , 0.8225987 ],
        [0.60302126, 0.7894051 , 0.75514424],
        [0.84680235, 0.50175667, 0.9435731 ],
        ...,
        [0.5553323 , 0.42468846, 0.06064665],
        [0.280002  , 0.473431  , 0.06675506],
        [0.36964417, 0.8351555 , 0.3773389 ]],

       ...,

       [[0.64310145, 0.73654306, 0.46824265],
        [0.03

In [113]:
# Find the min and max values of the tensor you created in 6.
print("min value: ", tf.reduce_min(tensor_3))
print("max value: ", tf.reduce_max(tensor_3))

min value:  tf.Tensor(5.4836273e-06, shape=(), dtype=float32)
max value:  tf.Tensor(0.99999785, shape=(), dtype=float32)


In [114]:
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor_4 = create_tensor((1, 224, 224, 3))
tensor_squeezed = tf.squeeze(tensor_4)

print(tensor_4.shape)
print(tensor_squeezed.shape)

(1, 224, 224, 3)
(224, 224, 3)


In [115]:
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor_5 = tf.constant(np.random.randint(1, high=11, size=10), shape=(10))
print(tensor_5)
print(tensor_5.shape)

tf.Tensor([4 1 5 9 7 3 2 7 7 2], shape=(10,), dtype=int64)
(10,)


In [116]:
# One-hot encode the tensor you created in 9.

encoded_tensor = tf.one_hot(tensor_5, depth=10)
print(encoded_tensor)

tf.Tensor(
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
